// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBXzPyowBml2jHqv_Ae8IXlNB4RoMm0Dw',
    appId: '1:279938936500:web:c8e8ee3d11fb540022b1e1',
    messagingSenderId: '279938936500',
    projectId: 'goods-shipping-company',
    authDomain: 'goods-shipping-company.firebaseapp.com',
    storageBucket: 'goods-shipping-company.appspot.com',
    measurementId: 'G-CVN23R0FNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKHNA0RmZ4gmdh6X4W4kHfInBLVRYphko',
    appId: '1:279938936500:android:b7323dbcdb39a49422b1e1',
    messagingSenderId: '279938936500',
    projectId: 'goods-shipping-company',
    storageBucket: 'goods-shipping-company.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtqwkRuubkTNL0odohzL3xbcBRelOs0yg',
    appId: '1:279938936500:ios:95184cd06e8635ee22b1e1',
    messagingSenderId: '279938936500',
    projectId: 'goods-shipping-company',
    storageBucket: 'goods-shipping-company.appspot.com',
    iosBundleId: 'com.example.compan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtqwkRuubkTNL0odohzL3xbcBRelOs0yg',
    appId: '1:279938936500:ios:5a8cc030c06417ae22b1e1',
    messagingSenderId: '279938936500',
    projectId: 'goods-shipping-company',
    storageBucket: 'goods-shipping-company.appspot.com',
    iosBundleId: 'com.example.compan.RunnerTests',
  );
}
